#include "C3PCH.h"
#include "dx_graphics.h"

const PrimInfo PRIM_INFO[] = {
  {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST, 3, 3, 0},
  {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP, 3, 1, 2},
  {D3D11_PRIMITIVE_TOPOLOGY_LINELIST, 2, 2, 0},
  {D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP, 2, 1, 1},
  {D3D11_PRIMITIVE_TOPOLOGY_POINTLIST, 1, 1, 0},
  {D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED, 0, 0, 0},
};
